title:              "라이프랩[인생실험실]"
tagline:            "나를 찾아보기로 했다"
email:              "lalasy619@gmail.com"
description:        "어른이 되었는데도 나를 잘 모르겠어서 시작하는 블로그"
author:             "SYPark"
baseurl:            "/"
url:                "https://slifelab.com/"
locale:             "ko_KR"
thumbnail:          "/img/lifelab_thumbnail.png"

# Social Profiles

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: raipeuraeb-insaengsilheomsil
